/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['td.today[_ngcontent-%COMP%]{\n    background: #337ab7;\n    color: #fff;\n}\ntd[_ngcontent-%COMP%]{\n    text-align: center;\n    cursor: pointer;\n}\ntd[_ngcontent-%COMP%]:hover{\n    background: #eee;\n}\n.header[_ngcontent-%COMP%]   .lt[_ngcontent-%COMP%], .header[_ngcontent-%COMP%]   .gt[_ngcontent-%COMP%]{\n    cursor: pointer;\n    width: 100%;\n}\n.datepicker[_ngcontent-%COMP%]{\n    width: 220px;\n}\n.header-text[_ngcontent-%COMP%]{\n    width: 180px !important;\n    display: inline-block;\n    text-align: center;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NhbnRvc2gvUHJvamVjdHMvYW5ndWxhci9uZy1kYXRlcGlja2VyL3NyYy9hcHAvZGF0ZXBpY2tlci9kYXRlcGlja2VyL2RhdGVwaWNrZXIuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9zYW50b3NoL1Byb2plY3RzL2FuZ3VsYXIvbmctZGF0ZXBpY2tlci9zcmMvYXBwL2RhdGVwaWNrZXIvZGF0ZXBpY2tlci9kYXRlcGlja2VyLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
