/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './datepicker-input.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../datepicker/datepicker.component.ngfactory';
import * as i3 from '../../../../../src/app/datepicker/datepicker/datepicker.component';
import * as i4 from '../../../../../src/app/datepicker/datepicker-input/datepicker-input.component';
import * as i5 from '@angular/common';
import * as i6 from '../../../../../src/app/datepicker/date.service';
const styles_DatepickerInputComponent:any[] = [i0.styles];
export const RenderType_DatepickerInputComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_DatepickerInputComponent,data:{}});
function View_DatepickerInputComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-datepicker',
      ([] as any[]),(null as any),(null as any),(null as any),i2.View_DatepickerComponent_0,
      i2.RenderType_DatepickerComponent)),i1.ɵdid(1,114688,(null as any),0,i3.DatepickerComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export function View_DatepickerInputComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),0,'input',[['type',
      'text']],(null as any),[[(null as any),'click']],(_v,en,$event) => {
    var ad:boolean = true;
    var _co:i4.DatepickerInputComponent = _v.component;
    if (('click' === en)) {
      const pd_0:any = ((<any>_co.openDatePicker()) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),
      i1.ɵand(16777216,(null as any),(null as any),1,(null as any),View_DatepickerInputComponent_1)),
      i1.ɵdid(3,16384,(null as any),0,i5.NgIf,[i1.ViewContainerRef,i1.TemplateRef],
          {ngIf:[0,'ngIf']},(null as any))],(_ck,_v) => {
    var _co:i4.DatepickerInputComponent = _v.component;
    const currVal_0:any = _co.show;
    _ck(_v,3,0,currVal_0);
  },(null as any));
}
export function View_DatepickerInputComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),2,'app-datepicker-input',
      ([] as any[]),(null as any),(null as any),(null as any),View_DatepickerInputComponent_0,
      RenderType_DatepickerInputComponent)),i1.ɵprd(4608,(null as any),i6.DateService,
      i6.DateService,([] as any[])),i1.ɵdid(2,114688,(null as any),0,i4.DatepickerInputComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,2,0);
  },(null as any));
}
export const DatepickerInputComponentNgFactory:i1.ComponentFactory<i4.DatepickerInputComponent> = i1.ɵccf('app-datepicker-input',
    i4.DatepickerInputComponent,View_DatepickerInputComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NhbnRvc2gvUHJvamVjdHMvYW5ndWxhci9uZy1kYXRlcGlja2VyL3NyYy9hcHAvZGF0ZXBpY2tlci9kYXRlcGlja2VyLWlucHV0L2RhdGVwaWNrZXItaW5wdXQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3NhbnRvc2gvUHJvamVjdHMvYW5ndWxhci9uZy1kYXRlcGlja2VyL3NyYy9hcHAvZGF0ZXBpY2tlci9kYXRlcGlja2VyLWlucHV0L2RhdGVwaWNrZXItaW5wdXQuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvc2FudG9zaC9Qcm9qZWN0cy9hbmd1bGFyL25nLWRhdGVwaWNrZXIvc3JjL2FwcC9kYXRlcGlja2VyL2RhdGVwaWNrZXItaW5wdXQvZGF0ZXBpY2tlci1pbnB1dC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3NhbnRvc2gvUHJvamVjdHMvYW5ndWxhci9uZy1kYXRlcGlja2VyL3NyYy9hcHAvZGF0ZXBpY2tlci9kYXRlcGlja2VyLWlucHV0L2RhdGVwaWNrZXItaW5wdXQuY29tcG9uZW50LnRzLkRhdGVwaWNrZXJJbnB1dENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxpbnB1dCB0eXBlPVwidGV4dFwiIChjbGljayk9XCJvcGVuRGF0ZVBpY2tlcigpXCI+XG48YXBwLWRhdGVwaWNrZXIgKm5nSWY9XCJzaG93XCI+PC9hcHAtZGF0ZXBpY2tlcj4iLCI8YXBwLWRhdGVwaWNrZXItaW5wdXQ+PC9hcHAtZGF0ZXBpY2tlci1pbnB1dD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0NBO01BQUE7dUNBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7b0JBREE7TUFBQTtJQUFBO0lBQUE7SUFBbUI7TUFBQTtNQUFBO0lBQUE7SUFBbkI7RUFBQSxnQ0FBOEMsMENBQzlDO2FBQUE7YUFBQTtVQUFBOztJQUFnQjtJQUFoQixXQUFnQixTQUFoQjs7OztvQkNEQTtNQUFBO3lDQUFBO3FCQUFBLHNCQUFBO01BQUE7SUFBQTs7OzsifQ==
