/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './datepicker/datepicker-input/datepicker-input.component.ngfactory';
import * as i3 from '../../../src/app/datepicker/datepicker-input/datepicker-input.component';
import * as i4 from '../../../src/app/app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'ng-datepicker',
      [['class','ng-datepicker']],(null as any),(null as any),(null as any),i2.View_DatepickerInputComponent_0,
      i2.RenderType_DatepickerInputComponent)),i1.ɵdid(1,49152,(null as any),0,i3.DatepickerInputComponent,
      ([] as any[]),{customFormatDate:[0,'customFormatDate']},(null as any))],(_ck,
      _v) => {
    var _co:i4.AppComponent = _v.component;
    const currVal_0:any = _co.getDate;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(1,49152,(null as any),0,i4.AppComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i4.AppComponent> = i1.ɵccf('app-root',
    i4.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NhbnRvc2gvUHJvamVjdHMvYW5ndWxhci9uZy1kYXRlcGlja2VyL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9zYW50b3NoL1Byb2plY3RzL2FuZ3VsYXIvbmctZGF0ZXBpY2tlci9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9zYW50b3NoL1Byb2plY3RzL2FuZ3VsYXIvbmctZGF0ZXBpY2tlci9zcmMvYXBwL2FwcC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3NhbnRvc2gvUHJvamVjdHMvYW5ndWxhci9uZy1kYXRlcGlja2VyL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8bmctZGF0ZXBpY2tlciBbY3VzdG9tRGF0ZV09XCJnZXREYXRlXCI+PC9uZy1kYXRlcGlja2VyPiIsIjxhcHAtcm9vdD48L2FwcC1yb290PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7NENBQUEsVUFBQTtNQUFBOzs7SUFBZTtJQUFmLFdBQWUsU0FBZjs7OztvQkNBQTtNQUFBO2FBQUE7VUFBQTs7OyJ9
